# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4ae1997b1ef7478b3d591036fa070d7f370fa262a34e7656ca5311b5987ded16680d8f33573a98970746f1aa4efc5a36da8711988ac067a566ff2c52035d7e70

test:
  secret_key_base: 2d6737270241abf4066608f8e869697a054669c83f43c97cc4c60d29e7d3f55c1020951d50fa48bf2aa0b40b947b2e11d770a6e87ab7077360807568d0de9868

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
